pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
      - ./dist
    volumes:
      - /tmp/cache:/cache

  build:
    image: node
    commands:
      - npm install
      - npm run build

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
      - ./dist
    volumes:
      - /tmp/cache:/cache

  deploy:
    image: docker
    commands:
      - docker build --rm -t zullin/vunite .
      - docker run --rm zullin/vunite
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock